"""modify field length

Revision ID: 2096049a36c3
Revises: 635b9650ffdf
Create Date: 2020-11-06 13:27:28.763560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2096049a36c3'
down_revision = '635b9650ffdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('iislog', 'cs_uri_query',
               existing_type=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('iislog', 'cs_uri_stem',
               existing_type=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('iislog', 'sc_status',
               existing_type=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('iislog', 'sc_status',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('iislog', 'cs_uri_stem',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('iislog', 'cs_uri_query',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    # ### end Alembic commands ###
