"""add iis_log model

Revision ID: 6cc5acd6c04f
Revises: 2fbf4f1f8084
Create Date: 2020-11-06 13:15:25.745819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc5acd6c04f'
down_revision = '2fbf4f1f8084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
